name: flutter_absolute_path
description: A flutter plugin that finds the absolute path of a file in iOS or Android devices.
version: 1.0.6
author: Kasem SAEED<kasem.jaffer@gmail.com>
homepage: https://github.com/KasemJaffer/flutter_absolute_path

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.kasem.flutter_absolute_path
    pluginClass: FlutterAbsolutePathPlugin
